version: '2'
services:
    jhipstersampleapplicationfirst-app:
        image: jhipstersampleapplicationfirst
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplicationfirst-mysql:3306/jhipstersampleapplicationfirst?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersampleapplicationfirst-mysql:
        extends:
            file: mysql.yml
            service: jhipstersampleapplicationfirst-mysql
